version: "3.5"

services:
  api01: &api
    build:
      context: .
    hostname: api1
    environment:
      PORT: 3000
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api2
    ports:
      - "3000:3000"

  # rinha-lb-tcp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.lb-tcp
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "100MB"

  rinha-lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "100MB"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
