version: "3.5"

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile.app
    hostname: api1
    network_mode: host
    depends_on:
      - db
    environment:
      PORT: 9998
      DB: "0.0.0.0:9995"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api2
    environment:
      PORT: 9997
      DB: "0.0.0.0:9995"

  db:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      PORT: 9995
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  rinha-lb-tcp:
    build:
      context: .
      dockerfile: Dockerfile.lb-tcp
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  # rinha-lb:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.lb
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "100MB"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "100MB"

# networks:
#   default:
#     driver: bridge
#     name: rinha-nginx-2024q1
