version: "3.5"

services:
  api01: &api
    build:
      context: .
    command: /app/rinha-app
    hostname: api1
    network_mode: host
    depends_on:
      - db
    environment:
      UNIX_SOCKET: /app/unix-sockets/rinha-app1.socket
      DB: /app/unix-sockets/rinha-espora_server.socket
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    volumes:
      - sockets:/app/unix-sockets

  api02:
    <<: *api
    hostname: api2
    environment:
      UNIX_SOCKET: /app/unix-sockets/rinha-app2.socket
      DB: /app/unix-sockets/rinha-espora_server.socket

  db:
    build:
      context: .
    command: /app/rinha-espora-server
    network_mode: host
    environment:
      UNIX_SOCKET: /app/unix-sockets/rinha-espora_server.socket
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"
    volumes:
      - sockets:/app/unix-sockets

  lb:
    build:
      context: .
    command: /app/rinha-load-balancer-tcp
    depends_on:
      - api01
      - api02
    environment:
      PORT: 9999
      UPSTREAMS: "/app/unix-sockets/rinha-app1.socket,/app/unix-sockets/rinha-app2.socket"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
    volumes:
      - sockets:/app/unix-sockets

volumes:
  sockets:
    name: unix-sockets
