version: "3.5"

services:
  api01: &api
    build:
      context: .
    command: /app/rinha-app
    hostname: api1
    network_mode: host
    depends_on:
      - db
    environment:
      PORT: 9998
      DB: "0.0.0.0:9995"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api2
    environment:
      PORT: 9997
      DB: "0.0.0.0:9995"

  db:
    build:
      context: .
    command: /app/rinha-espora-server
    network_mode: host
    environment:
      PORT: 9995
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  lb:
    build:
      context: .
    command: /app/rinha-load-balancer-tcp
    depends_on:
      - api01
      - api02
    environment:
      PORT: 9999
      UPSTREAMS: "0.0.0.0:9997,0.0.0.0:9998"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
