version: "3.5"

services:
  api01: &api
    build:
      context: .
    command: /app/rinha-espora-embedded
    hostname: api1
    network_mode: host
    environment:
      UNIX_SOCKET: /app/unix-sockets/rinha-app1.socket
      DB: "/db"
    volumes:
      - db:/db
      - sockets:/app/unix-sockets
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api2
    environment:
      UNIX_SOCKET: /app/unix-sockets/rinha-app2.socket
      DB: "/db"

  lb:
    build:
      context: .
    command: /app/rinha-load-balancer-tcp
    depends_on:
      - api01
      - api02
    environment:
      PORT: 9999
      UPSTREAMS: "/app/unix-sockets/rinha-app1.socket,/app/unix-sockets/rinha-app2.socket"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"
    volumes:
      - sockets:/app/unix-sockets

volumes:
  db:
    name: db
  sockets:
    name: unix-sockets
