[package]
name = "rinha-load-balancer-tcp"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
